### ISSUE TITLE
建议提供官方的docker-compose.yml文件

### ISSUE THREAD

**Issue by Margular** [chennqqi/godnslog#15]
我这里有一份参考：
```
version: "3.5"

services:
  godnslog:
    image: sort/godnslog
    environment:
      - GIN_MODE=release
    ports:
      - "127.0.0.1:10080:8080"    # 反向代理模式
      - "53:53/udp"
    restart: always
    command: serve -domain yourdomain.com -4 x.x.x.x
    volumes:
      - ./godnslog.db:/app/godnslog.db   # 持久化存储
```
